seed_everything: 42
trainer:
  max_epochs: 120
  accelerator: auto
  devices: auto
  logger:
    class_path: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
    init_args:
      save_dir: "logs/"
      name: "imagenet_8_cross_attend_share"
      version: null
      default_hp_metric: true
  accumulate_grad_batches: 4
model:
  learning_rate: 0.004
  weight_decay: 0.05
  num_freq_bands: 64
  max_freq: 224
  depth: 8
  num_latents: 512
  latent_dim: 1024
  self_per_cross_attn: 6
  weight_share: true
  compile: true
data:
  batch_size: 8
  data_dir: "data/imagenet"